services:
  db:
    image: postgres
    ports:
    - "5432:5432"
    volumes:
    - postgres-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 5
  api:
    build:
      context: ./
      dockerfile: ./Dockerfile
    command: start_django_development_server
    volumes:
    - .:/rently_api
    env_file:
    - .env.example
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
volumes:
  postgres-data: